language: php

sudo: false

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
    # disable xdebug if available
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    # disable default memory limit
    - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI

install:
    # flags to pass to install
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    # install dependencies using system provided composer binary
    - composer install $flags

before_script:
    # make sure git tests do not complain about user/email not being set
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script:
    # run test suite directories in parallel using GNU parallel
    - ./bin/phpunit -c phpunit.xml.dist